# Generated by Django 4.2 on 2026-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_batch_pharmacy_drug_pharmacy_supplier_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='training_id',
            field=models.CharField(blank=True, help_text='ID from training dataset', max_length=50, null=True),
        ),
    ]
