# Generated by Django 4.2 on 2026-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='ai_confidence',
            field=models.IntegerField(default=0, help_text='AI confidence score (0-100)'),
        ),
    ]
