# Generated by Django 4.2 on 2026-03-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('prescriptions', '0002_interactionlog_ai_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionlog',
            name='drug_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug1', to='inventory.drug'),
        ),
    ]
