# Generated by Django 4.2 on 2026-03-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_interactionlog_drug_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionlog',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='prescriptions.prescription'),
        ),
    ]
