# Generated by Django 4.2 on 2026-04-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_pharmacy'),
        ('prescriptions', '0004_alter_interactionlog_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy'),
        ),
    ]
