# Generated by Django 4.2 on 2026-04-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy'),
        ),
    ]
