# Generated by Django 4.2 on 2026-06-05 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_userprofile_pharmacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PendingUserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('requested_pharmacy_name', models.CharField(max_length=200)),
                ('requested_role', models.CharField(choices=[('admin', 'Administrator'), ('pharmacist', 'Pharmacist'), ('technician', 'Pharmacy Technician')], default='technician', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_request', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_requests', to='accounts.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
